In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
from qubingx.cop.given import Given
from qubingx.utils import QubingUtils
from qubingx.solver.sa import SAParams, SA


In [2]:
utils = QubingUtils()
qubo = utils.random_model(n=10, seed=0)
qubo

array([[ 0, -5, -2, -2,  2,  4, -2,  0, -3, -1],
       [ 0,  1,  3,  3,  5, -4,  1,  2,  2,  3],
       [ 0,  0,  4,  3,  4, -1, -2, -5, -2,  0],
       [ 0,  0,  0,  3, -4, -2, -2, -2,  2, -5],
       [ 0,  0,  0,  0,  5, -1,  2, -2, -3,  2],
       [ 0,  0,  0,  0,  0,  0,  1,  3, -1, -4],
       [ 0,  0,  0,  0,  0,  0, -4,  2,  4,  4],
       [ 0,  0,  0,  0,  0,  0,  0,  4,  5, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1, -2],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -5]])

In [3]:
model = Given(mtx_all=qubo)

In [4]:
model.to_bqm()

BinaryQuadraticModel({0: 0.0, 1: 1.0, 2: 4.0, 3: 3.0, 4: 5.0, 5: 0.0, 6: -4.0, 8: -1.0, 9: -5.0, 7: 4.0}, {(1, 0): -5.0, (2, 0): -2.0, (2, 1): 3.0, (3, 0): -2.0, (3, 1): 3.0, (3, 2): 3.0, (4, 0): 2.0, (4, 1): 5.0, (4, 2): 4.0, (4, 3): -4.0, (5, 0): 4.0, (5, 1): -4.0, (5, 2): -1.0, (5, 3): -2.0, (5, 4): -1.0, (6, 0): -2.0, (6, 1): 1.0, (6, 2): -2.0, (6, 3): -2.0, (6, 4): 2.0, (6, 5): 1.0, (8, 0): -3.0, (8, 1): 2.0, (8, 2): -2.0, (8, 3): 2.0, (8, 4): -3.0, (8, 5): -1.0, (8, 6): 4.0, (9, 0): -1.0, (9, 1): 3.0, (9, 3): -5.0, (9, 4): 2.0, (9, 5): -4.0, (9, 6): 4.0, (9, 8): -2.0, (7, 1): 2.0, (7, 2): -5.0, (7, 3): -2.0, (7, 4): -2.0, (7, 5): 3.0, (7, 6): 2.0, (7, 8): 5.0, (7, 9): -1.0}, 0.0, 'BINARY')

In [5]:
model.h_all, model.h_obj, model.h_constraint

(array([[ 0, -5, -2, -2,  2,  4, -2,  0, -3, -1],
        [ 0,  1,  3,  3,  5, -4,  1,  2,  2,  3],
        [ 0,  0,  4,  3,  4, -1, -2, -5, -2,  0],
        [ 0,  0,  0,  3, -4, -2, -2, -2,  2, -5],
        [ 0,  0,  0,  0,  5, -1,  2, -2, -3,  2],
        [ 0,  0,  0,  0,  0,  0,  1,  3, -1, -4],
        [ 0,  0,  0,  0,  0,  0, -4,  2,  4,  4],
        [ 0,  0,  0,  0,  0,  0,  0,  4,  5, -1],
        [ 0,  0,  0,  0,  0,  0,  0,  0, -1, -2],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -5]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

In [6]:
model.to_dict()

{(0, 1): -5,
 (0, 2): -2,
 (0, 3): -2,
 (0, 4): 2,
 (0, 5): 4,
 (0, 6): -2,
 (0, 8): -3,
 (0, 9): -1,
 (1, 1): 1,
 (1, 2): 3,
 (1, 3): 3,
 (1, 4): 5,
 (1, 5): -4,
 (1, 6): 1,
 (1, 7): 2,
 (1, 8): 2,
 (1, 9): 3,
 (2, 2): 4,
 (2, 3): 3,
 (2, 4): 4,
 (2, 5): -1,
 (2, 6): -2,
 (2, 7): -5,
 (2, 8): -2,
 (3, 3): 3,
 (3, 4): -4,
 (3, 5): -2,
 (3, 6): -2,
 (3, 7): -2,
 (3, 8): 2,
 (3, 9): -5,
 (4, 4): 5,
 (4, 5): -1,
 (4, 6): 2,
 (4, 7): -2,
 (4, 8): -3,
 (4, 9): 2,
 (5, 6): 1,
 (5, 7): 3,
 (5, 8): -1,
 (5, 9): -4,
 (6, 6): -4,
 (6, 7): 2,
 (6, 8): 4,
 (6, 9): 4,
 (7, 7): 4,
 (7, 8): 5,
 (7, 9): -1,
 (8, 8): -1,
 (8, 9): -2,
 (9, 9): -5}

In [7]:
model.show(group="all")

In [8]:
sa_params = SAParams(
    beta_range=[1/1000, 1/0.1],
    num_reads=10,
    seed=0,
)
sa = SA(sa_params)

In [9]:
result1 = sa.sample(bqm=model.to_bqm())
result1

(array([-17., -17., -17., -17., -17., -17., -17., -17., -17., -17.]),
 array([[1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 1, 0, 1, 0, 1, 0, 0, 1, 1]], dtype=int8))

In [10]:
result2 = sa.sample(bqm=model.to_bqm(), raw=True)
result2

(array([-17., -17., -17., -17., -17., -17., -17., -17., -17., -17.]),
 array([[1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
        [1, 1, 0, 1, 0, 1, 0, 0, 1, 1]], dtype=int8),
 SampleSet(rec.array([([1, 0, 0, 1, 0, 1, 0, 0, 1, 1], -17., 1),
            ([1, 0, 0, 1, 0, 1, 0, 0, 1, 1], -17., 1),
            ([1, 0, 0, 1, 0, 1, 0, 0, 1, 1], -17., 1),
            ([1, 0, 0, 1, 0, 1, 0, 0, 1, 1], -17., 1),
            ([1, 0, 0, 1, 0, 1, 0, 0, 1, 1], -17., 1),
            ([1, 0, 0, 1, 0, 1, 0, 0, 1, 1], -17., 1),
            ([1, 0, 0, 1, 0, 1, 0, 0, 1, 1], -17., 1),
            ([1, 1, 0, 1, 0, 1, 0, 0, 1, 1], -17., 1),
            ([1, 1, 0, 1, 0, 1, 0, 0, 1, 1], -17., 1),
           